name: Generar y Desplegar Mapa

on:
  schedule:
    - cron: '0 * * * *' # Se ejecuta a la hora en punto, cada hora
  workflow_dispatch: # Permite la ejecución manual desde la pestaña Actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install folium pyproj pandas openpyxl

      - name: Ejecutar script para generar el mapa
        run: python generar_mapa.py

      - name: Desplegar a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          # El publish_dir es el directorio raíz porque mapa_cajas.html se crea ahí.
          # Los archivos se publicarán en una rama llamada 'gh-pages'.
